[changelog]
# changelog header
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

---
"""

# template for the changelog body
body = """
{% if version %}\
## [{{ version }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper }}
{% for commit in commits %}
- {% if commit.breaking %}**BREAKING** {% endif %}{{ commit.message | upper_first }} ([`{{ commit.id | truncate(length=7, end="") }}`]({{ commit.link | replace(from="#", to="") }}))
{%- endfor %}
{% endfor %}\n
"""


# remove the leading and trailing whitespace from the template
trim = true

# changelog footer
footer = ""

# Regex for parsing conventional commits
[[git.commit_parsers]]
message = "^feat"
group = "Added"

[[git.commit_parsers]]
message = "^fix"
group = "Fixed"

[[git.commit_parsers]]
message = "^doc"
group = "Documentation"

[[git.commit_parsers]]
message = "^perf"
group = "Performance"

[[git.commit_parsers]]
message = "^refactor"
group = "Changed"

[[git.commit_parsers]]
message = "^test"
group = "Testing"

[[git.commit_parsers]]
message = "^chore"
skip = true

[[git.commit_parsers]]
message = "^ci"
skip = true

[[git.commit_parsers]]
message = "^style"
skip = true

[[git.commit_parsers]]
body = ".*breaking change.*"
group = "Breaking Changes"
